### ISSUE TITLE
Is this plugin complete?

### ISSUE THREAD

**Issue by ghost** [jwindgassen/LargeObjectReplication#1]
Hi, I also want to replicate a large sized object, is this plugin complete?

**Comment by jwindgassen** [comment]
Hey, thanks for your interest. The Plugins works on a basic level, but I would still call it WIP.
IIRC, you can definitely replicate large data in the current state. But at the moment all data is replicated instantly when a user joins or the object is spawned, which results (at least for me) in a lagging application while it is replicating.

But my Objects are also a few MB in size, so that's quite large. If the objects are not that huge in size, it might work better for you.

**Comment by ghost** [comment]
Oh, I see. I was trying it the other day with UE 5.4.3 and got a runtime error (access violation, I think), so I was wondering if it was in production and not working. I modified it somewhat to make it work, so I was thinking of sending pull requests if you recognize the same...

By the way, I borrowed some of your ideas and made a plugin that allows you to send huge data by sending RPCs in small pieces instead of replicate. (https://github.com/Udon-Tobira/TransceiveLargeDataPlugin)
The main difference is that you can send data from the client to the server.
Take a look if you are interested. (WIP)

**Comment by jwindgassen** [comment]
It's not in production (yet). I have a feature branch where I tried to integrate the Plugin and make it work, but I had to work on other stuff before I could complete that.
There is still much to be done here, but if you have some improvements, feel free to open a PR.

Regarding the RPCs: I also tried that, you can see that in the `test/RPCs` branch. The idea was to have some kind of centralized data manager on the server, so different clients could query different Blobs of data from it. I think, I also tried allowing clients to send data to the server, but sending data from client to server is always a bit difficult. I don't really remember how far I got there and why it didn't really work, but check it out if you are interested :)

**Comment by ghost** [comment]
Oh, you also tried RPC. I ended up sending data via RPC and found that if I sent too many in a short time, I got a "Warning: CreateSavedMove: Hit limit of 96 saved moves (timing out or very bad ping?)" (probably from CharacterMovement ), causing the client and server to be out of sync for a while. However, if I send the data slowly, it takes too long to finish sending the data.

I thought that as long as we were using the same network driver as Character, I probably wouldn't be able to send the data as fast as I wanted, so I finally used beacons (beacons use a different driver than the network driver of Character, GameNetDriver) to send and receive large datas between the client and server without causing such problems, even at high speeds!

I'll publish a sample repository of that someday, but anyway, your program was very helpful. Thank you!
